In [1]:
import numpy as np

In [2]:
def Sigmoid(x):
    return 1/(1+np.exp(-x))

NameError: name 'sigmoid' is not defined

In [5]:
def Hessian(input_data, label, beta, length):
    gradient = np.mat([0]*length, dtype = np.float64).T
    hessian = np.mat([[0]*length]*length, dtype = np.float64)
    for i in range(len(input_data)):
        row = np.mat(list(input_data.iloc[i])).T
        pro0 = float(Sigmoid(-beta*row))
        gradient += row*(1-pro0-label[i])
        hessian += row * row.T *(1-pro0)*pro0
    return gradient, hessian  

In [6]:
def Newton(input_data, label, iter_num = 20):
    length =len(input_data.iloc[0])
    beta_init = np.mat([0]*length)
    for i in range(iter_num):
        gradient, hessian = Hessian(input_data, label, beta_init, length)
        beta = beta_init - (hessian.I * gradient).T
        print(beta)
        beta_init = beta
    return beta    

In [7]:
import pandas as pd
df = pd.read_csv('/root/ex3.2.csv', sep= '\t' )

In [ ]:
np.mat(list(df.iloc[3]))

In [8]:
data = df[df.columns[:-1]]
data['e'] = [1]*len(data)

In [9]:
label = df[df.columns[-1]]

In [ ]:
data.head()

In [10]:
b= Newton(data, label)

[[ 0.35348642 -0.38387881  2.6338204 ]]
[[ 0.55277077 -0.6689599   4.73812723]]
[[ 0.73916086 -1.00289552  7.26889383]]
[[ 0.94117862 -1.3870536  10.1760878 ]]
[[ 1.12941789 -1.74673676 12.86797032]]
[[ 1.23189457 -1.95422517 14.39976378]]
[[ 1.25280867 -2.00079391 14.73864574]]
[[ 1.25358179 -2.00266972 14.75212626]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]
[[ 1.25358296 -2.00267269 14.75214744]]


In [ ]:
 r= np.mat(list(data.iloc[0])).T

In [ ]:
r*r.T*2*1

In [ ]:
a = np.mat([1])

In [ ]:
a

In [ ]:
r*r.T*np.float(a)